version: "3.9"

services:
  api:
    build:
      context: ./api
      args:
        - DEV=true
    hostname: api
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - ALLOWED_HOSTS=api,127.0.0.1,localhost
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  cron:
    build:
      context: ./cron
    volumes:
      - ./cron/app:/app
    command: crond -f -l 2
    depends_on:
      - api

volumes:
  dev-db-data:
